[WIP] Contact tests from nucypher repo
nucypher/nucypher-contracts pull request #20
Opened 2022-02-21 09:56 UTC by vzotova

Moves tests from nucypher repo + adjusting them for using brownie

2022-03-30 13:44 UTC, theref approved these changes

2022-03-30 19:15 UTC, manumonti requested changes
Wow! Nice work!

2022-03-30 19:15 UTC, KPrasch commented
Awesome!

2022-03-30 19:54 UTC, derekpierre approved these changes
🎸

2022-03-31 07:21 UTC, vzotova commented on tests/application/test_operator.py
> +    creator, staking_provider_1, staking_provider_2, staking_provider_3, staking_provider_4, operator1, operator2, \
There is small issue with pre-commit hooks with this file, after prettifying it moves all variables at one line and fails when check line length. I commited with 'no-verify' and this is why missed error.
Anyway I changed line
✔️

2022-03-31 09:14 UTC, manumonti commented on tests/application/test_operator.py
> +    creator, staking_provider_1, staking_provider_2, staking_provider_3, staking_provider_4, operator1, operator2, \
Super!

2022-03-31 09:15 UTC, manumonti approved these changes

2022-03-31 10:09 UTC, cygnusv approved these changes

2022-03-31 15:50 UTC, merged