[WIP] Automated DKG Inititaiton
nucypher/nucypher-contracts pull request #338
Opened 2024-09-24 16:40 UTC by KPrasch

**Type of PR:**
Automation

**Required reviews:** 
2

**What this does:**
Automatically execute new DKGs on a schedule using GitHub Actions.

2025-03-14 13:40 UTC, derekpierre commented
Would it make sense to merge this into an epic for now to ensure the script only runs when needed? Merging into `main` will likely trigger the cron job, but without the subsequent scripts (data collection, report generation, etc.), we may want to hold off on running on `mainnet` for now.

2025-03-18 12:21 UTC, manumonti requested changes

2025-03-18 12:21 UTC, manumonti commented on scripts/initiate_ritual.py
> +)
Does the --autosign parameter work for you? I ran the command on lynx with this and I still had to type the signer password every time.

Also,


```suggestion
@click.option(
    "--autosign",
    help="Allow the Ape account to automatically sign the transactions.",
    is_flag=True,
)
```

2025-03-18 12:24 UTC, manumonti requested changes

2025-03-18 12:24 UTC, manumonti commented on scripts/initiate_ritual.py
> +)
```suggestion
```suggestion
@click.option(
    "--heartbeat",
    help="Run a heartbeat check, whereby rituals will be initiated so every node is involved.",
    is_flag=True,
)
```
)
```

2025-03-18 13:39 UTC, manumonti requested changes
Maybe we should address the evaluation of the heartbeats in a subsequent PR (next iteration).

We could remove `evaluate_heartbeat.py` and `evaluate.yml` of this PR so we merge this first iteration in which we just initiate the heartbeat rituals.

WDYT?

2025-03-18 13:39 UTC, manumonti commented on deployment/utils.py
> +    return [sorted(list(pair)) for pair in zip_longest(it, it)]
I have this suggestion to address the TODO comment:

https://github.com/KPrasch/nucypher-contracts/pull/4

2025-03-18 13:39 UTC, manumonti commented on .github/workflows/heartbeat.yml
> +        path: rituals.json
```suggestion
        path: heartbeat_rituals.json
```

2025-03-18 15:23 UTC, KPrasch commented on .github/scripts/eval_dkg.sh
> +--artifact rituals.json \
✔️

2025-03-18 15:23 UTC, KPrasch commented on .github/workflows/heartbeat.yml
> +        path: rituals.json
✔️

2025-03-18 15:23 UTC, KPrasch commented on deployment/utils.py
> +    return [sorted(list(pair)) for pair in zip_longest(it, it)]
Thank you! ✔️

2025-03-18 15:23 UTC, KPrasch commented on scripts/initiate_ritual.py
> +)
Let's have a closer look in a follow-up PR / issue.

2025-03-18 15:23 UTC, KPrasch commented on scripts/initiate_ritual.py
> +        duration = 86400  # default to 24h
💯 ✔️

2025-03-18 15:31 UTC, manumonti approved these changes

2025-03-18 15:47 UTC, derekpierre commented on scripts/initiate_ritual.py
> +        click.confirm(text="Are you sure you want to initiate these rituals?", abort=True)
Does this prompt have to be manually confirmed? If so, is this just temporary for now?

2025-03-18 15:47 UTC, derekpierre commented on .github/workflows/heartbeat.yml
> +        path: heartbeat-rituals.json
Does each round of heartbeats overwrite the heartbeat-rituals.json artifact? Just wondering if we happen not to process a heartbeat-rituals.json artifact before another round of heartbeats is performed?

2025-03-18 19:25 UTC, KPrasch commented on scripts/initiate_ritual.py
> +        click.confirm(text="Are you sure you want to initiate these rituals?", abort=True)
Yes - just temporary for now while we are manually testing 👍🏻

2025-03-19 13:33 UTC, manumonti approved these changes

2025-03-19 13:33 UTC, manumonti commented on deployment/utils.py
> +    In the realm of addresses, where keys unlock boundless potential,
🧘

2025-03-19 13:33 UTC, manumonti commented on deployment/utils.py
> +    return tuple(map(lambda group: tuple(sorted(group, key=str.lower)), groups))
great solution! I like it

2025-03-19 16:39 UTC, KPrasch commented on scripts/initiate_ritual.py
> +        click.confirm(text="Are you sure you want to initiate these rituals?", abort=True)
✔️

2025-03-19 16:40 UTC, merged

2025-03-19 18:58 UTC, derekpierre commented on .github/workflows/heartbeat.yml
> +        path: heartbeat-rituals.json
It's fine for now, just curious really.

Not sure if we need long-term storage since we will run the reporting script based on rituals in the heartbeat-rituals.json file, and once we do, the heartbeat-rituals.json file is not really needed anymore. Plus I guess we could always determine the rituals that were kicked off from on chain events on the day that the heartbeats were done anyway.